// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task1510.Data;

#nullable disable

namespace Task1510.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task1510.Data.Entity.Marka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marka");
                });

            modelBuilder.Entity("Task1510.Data.Entity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpecialModelID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialModelID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Task1510.Data.Entity.SpecialModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarkaID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarkaID");

                    b.ToTable("SpecialModels");
                });

            modelBuilder.Entity("Task1510.Data.Entity.Person", b =>
                {
                    b.HasOne("Task1510.Data.Entity.SpecialModel", "SpecialModel")
                        .WithMany()
                        .HasForeignKey("SpecialModelID");

                    b.Navigation("SpecialModel");
                });

            modelBuilder.Entity("Task1510.Data.Entity.SpecialModel", b =>
                {
                    b.HasOne("Task1510.Data.Entity.Marka", "Marka")
                        .WithMany("SpecialModels")
                        .HasForeignKey("MarkaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marka");
                });

            modelBuilder.Entity("Task1510.Data.Entity.Marka", b =>
                {
                    b.Navigation("SpecialModels");
                });
#pragma warning restore 612, 618
        }
    }
}
